-- MySQL Script generated by MySQL Workbench
-- Fri May 17 14:55:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EER
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EER
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EER` DEFAULT CHARACTER SET utf8 ;
USE `EER` ;

-- -----------------------------------------------------
-- Table `EER`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EER`.`tb_categorias` (
  `id` BIGINT NOT NULL,
  `nome_categoria` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EER`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EER`.`tb_usuario` (
  `id` BIGINT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EER`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EER`.`tb_produto` (
  `id` BIGINT NOT NULL,
  `nome_produto` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `quantidade` BIGINT NOT NULL,
  `categoria` BIGINT NULL,
  `usuario` BIGINT(45) NULL,
  `tb_produtocol` VARCHAR(45) NULL,
  `tb_categorias_id` BIGINT NOT NULL,
  `tb_usuario_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produto_tb_categorias_idx` (`tb_categorias_id` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_usuario1_idx` (`tb_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categorias`
    FOREIGN KEY (`tb_categorias_id`)
    REFERENCES `EER`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_usuario1`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `EER`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
